# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: mcs.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'mcs.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tmcs.proto\x12\x16ModuleContextStreaming\"+\n\nClientInfo\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0f\n\x07version\x18\x02 \x01(\t\"L\n\x11InitializeRequest\x12\x37\n\x0b\x63lient_info\x18\x01 \x01(\x0b\x32\".ModuleContextStreaming.ClientInfo\"C\n\x10InitializeResult\x12\x16\n\x0eserver_version\x18\x01 \x01(\t\x12\x17\n\x0fwelcome_message\x18\x02 \x01(\t\"\x12\n\x10ListToolsRequest\"3\n\x0eToolDefinition\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\"H\n\x0fListToolsResult\x12\x35\n\x05tools\x18\x01 \x03(\x0b\x32&.ModuleContextStreaming.ToolDefinition\"\xa1\x01\n\x0fToolCallRequest\x12\x11\n\ttool_name\x18\x01 \x01(\t\x12I\n\targuments\x18\x02 \x03(\x0b\x32\x36.ModuleContextStreaming.ToolCallRequest.ArgumentsEntry\x1a\x30\n\x0e\x41rgumentsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\";\n\rToolCallChunk\x12\x15\n\rcontent_chunk\x18\x01 \x01(\t\x12\x13\n\x0bsequence_id\x18\x02 \x01(\x05\x32\xbc\x02\n\rModuleContext\x12\x63\n\nInitialize\x12).ModuleContextStreaming.InitializeRequest\x1a(.ModuleContextStreaming.InitializeResult\"\x00\x12`\n\tListTools\x12(.ModuleContextStreaming.ListToolsRequest\x1a\'.ModuleContextStreaming.ListToolsResult\"\x00\x12\x64\n\x0eStreamToolCall\x12\'.ModuleContextStreaming.ToolCallRequest\x1a%.ModuleContextStreaming.ToolCallChunk\"\x00\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'mcs_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TOOLCALLREQUEST_ARGUMENTSENTRY']._loaded_options = None
  _globals['_TOOLCALLREQUEST_ARGUMENTSENTRY']._serialized_options = b'8\001'
  _globals['_CLIENTINFO']._serialized_start=37
  _globals['_CLIENTINFO']._serialized_end=80
  _globals['_INITIALIZEREQUEST']._serialized_start=82
  _globals['_INITIALIZEREQUEST']._serialized_end=158
  _globals['_INITIALIZERESULT']._serialized_start=160
  _globals['_INITIALIZERESULT']._serialized_end=227
  _globals['_LISTTOOLSREQUEST']._serialized_start=229
  _globals['_LISTTOOLSREQUEST']._serialized_end=247
  _globals['_TOOLDEFINITION']._serialized_start=249
  _globals['_TOOLDEFINITION']._serialized_end=300
  _globals['_LISTTOOLSRESULT']._serialized_start=302
  _globals['_LISTTOOLSRESULT']._serialized_end=374
  _globals['_TOOLCALLREQUEST']._serialized_start=377
  _globals['_TOOLCALLREQUEST']._serialized_end=538
  _globals['_TOOLCALLREQUEST_ARGUMENTSENTRY']._serialized_start=490
  _globals['_TOOLCALLREQUEST_ARGUMENTSENTRY']._serialized_end=538
  _globals['_TOOLCALLCHUNK']._serialized_start=540
  _globals['_TOOLCALLCHUNK']._serialized_end=599
  _globals['_MODULECONTEXT']._serialized_start=602
  _globals['_MODULECONTEXT']._serialized_end=918
# @@protoc_insertion_point(module_scope)
