# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import mcs_pb2 as mcs__pb2

GRPC_GENERATED_VERSION = '1.75.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in mcs_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ModuleContextStub(object):
    """The service definition: This is the collection of RPC methods your server will provide.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Initialize = channel.unary_unary(
                '/ModuleContextStreaming.ModuleContext/Initialize',
                request_serializer=mcs__pb2.InitializeRequest.SerializeToString,
                response_deserializer=mcs__pb2.InitializeResult.FromString,
                _registered_method=True)
        self.ListTools = channel.unary_unary(
                '/ModuleContextStreaming.ModuleContext/ListTools',
                request_serializer=mcs__pb2.ListToolsRequest.SerializeToString,
                response_deserializer=mcs__pb2.ListToolsResult.FromString,
                _registered_method=True)
        self.StreamToolCall = channel.unary_stream(
                '/ModuleContextStreaming.ModuleContext/StreamToolCall',
                request_serializer=mcs__pb2.ToolCallRequest.SerializeToString,
                response_deserializer=mcs__pb2.ToolCallChunk.FromString,
                _registered_method=True)


class ModuleContextServicer(object):
    """The service definition: This is the collection of RPC methods your server will provide.
    """

    def Initialize(self, request, context):
        """A simple unary call for the initial handshake and capability negotiation.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListTools(self, request, context):
        """A unary call to discover what tools the server has available.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamToolCall(self, request, context):
        """The core server-streaming method. The client sends one request, and the server
        streams back a sequence of chunks. This is perfect for streaming text or data.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ModuleContextServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Initialize': grpc.unary_unary_rpc_method_handler(
                    servicer.Initialize,
                    request_deserializer=mcs__pb2.InitializeRequest.FromString,
                    response_serializer=mcs__pb2.InitializeResult.SerializeToString,
            ),
            'ListTools': grpc.unary_unary_rpc_method_handler(
                    servicer.ListTools,
                    request_deserializer=mcs__pb2.ListToolsRequest.FromString,
                    response_serializer=mcs__pb2.ListToolsResult.SerializeToString,
            ),
            'StreamToolCall': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamToolCall,
                    request_deserializer=mcs__pb2.ToolCallRequest.FromString,
                    response_serializer=mcs__pb2.ToolCallChunk.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ModuleContextStreaming.ModuleContext', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ModuleContextStreaming.ModuleContext', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ModuleContext(object):
    """The service definition: This is the collection of RPC methods your server will provide.
    """

    @staticmethod
    def Initialize(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ModuleContextStreaming.ModuleContext/Initialize',
            mcs__pb2.InitializeRequest.SerializeToString,
            mcs__pb2.InitializeResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListTools(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ModuleContextStreaming.ModuleContext/ListTools',
            mcs__pb2.ListToolsRequest.SerializeToString,
            mcs__pb2.ListToolsResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamToolCall(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/ModuleContextStreaming.ModuleContext/StreamToolCall',
            mcs__pb2.ToolCallRequest.SerializeToString,
            mcs__pb2.ToolCallChunk.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
