# This workflow builds and publishes a Python package to PyPI when a push occurs on the main branch.

name: Publish Python Package to PyPI

on:
  push:
    branches: [ main ]
  workflow_dispatch: # Allows you to run this workflow manually from the Actions tab

jobs:
  build-and-publish:
    name: Build and publish Python 🐍 distributions to PyPI
    runs-on: ubuntu-latest
    # Specifies the environment name for trusted publishing
    environment: pypi
    # These permissions are essential for trusted publishing
    permissions:
      id-token: write  # This is required for OIDC authentication with PyPI

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      # --- Optional: Add your test steps here ---
      # - name: Install dependencies
      #   run: |
      #     python -m pip install --upgrade pip
      #     pip install -r requirements.txt
      #     pip install pytest
      # - name: Test with pytest
      #   run: |
      #     pytest

      - name: Build package
        run: |
          python -m pip install --upgrade pip
          pip install build
          python -m build

      - name: Publish package to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        # No password or API token is needed! The action automatically handles
        # the authentication with PyPI via the OIDC token.